export const methodologyMap = {
  accessibility: "Accessibility",
  agile: "Agile",
  composableDesign: "Composable Design",
  crabTesting: "Crab Testing",
  dependencyInjection: "Dependency Injection",
  mvc: "MVC",
  onPremHosting: "On-Prem Hosting",
  rest: "REST",
  seo: "SEO",
  serverless: "Serverless",
  tdd: "TDD",
} as const;

export const techMap = {
  apacheVelocity: "Apache Velocity",
  apollo: "Apollo",
  astro: "Astro",
  aws: "AWS",
  awsLambda: "AWS Lambda",
  azureAppService: "Azure App Service",
  bootstrap: "Bootstrap",
  cSharpDotNet: "C#/.NET",
  docker: "Docker",
  edgeDeployment: "Edge Deployment",
  entityFramework: "Entity Framework",
  esLint: "ESLint",
  github: "GitHub",
  gitlab: "GitLab",
  graphQl: "GraphQL",
  htmlCss: "HTML/CSS",
  i18next: "i18next",
  java: "Java",
  javascript: "JavaScript",
  jest: "Jest",
  jira: "Jira",
  laravel: "Laravel",
  mediatR: "MediatR",
  monorepo: "Monorepo",
  moq: "Moq",
  nestJs: "NestJS",
  nextJs: "NextJS",
  nextUi: "NextUI",
  node: "NodeJS",
  nx: "NX",
  php: "PHP",
  playwright: "Playwright",
  prisma: "Prisma",
  qwikCity: "QwikCity",
  react: "React",
  reactNative: "React Native",
  reactPdf: "ReactPDF",
  reactTestingLibrary: "React Testing Library",
  redux: "Redux",
  rust: "Rust",
  sanity: "Sanity",
  sitecore: "Sitecore",
  solid: "SolidJS",
  solidStart: "Solid Start",
  springBoot: "Spring Boot",
  sql: "SQL",
  stencil: "Stencil",
  storybook: "StoryBook",
  subversion: "Subversion (SVN)",
  tailwind: "Tailwind",
  twilio: "Twilio",
  typeGraphQl: "TypeGraphQL",
  typeOrm: "TypeORM",
  typeScript: "TypeScript",
  uswds: "United States Web Design System (USWDS)",
  vitest: "Vitest",
  vue: "Vue",
  webAssembly: "WebAssembly",
  webRtc: "WebRTC",
  webSockets: "WebSockets",
  xUnit: "XUnit",
  yii: "Yii",
  zod: "Zod",
} as const;


